### ISSUE TITLE
[BUG]page.pause() not work. popup a blank window

### ISSUE THREAD

**Issue by gster** [Kaliiiiiiiiii-Vinyzu/patchright#20]
### System info
- Playwright Version: [v1.40]
- Operating System: [Ubuntu 22.04, macOS 12.63]
- Browser: [Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```python
from undetected_playwright.async_api import async_playwright, Page

playwright_browser = await async_playwright().start()
browser_context = await playwright_browser["chromium"].launch_persistent_context(
          _path,
          executable_path="Chromium.app/Contents/MacOS/Chromium",
          ...)
 page = browser_context.pages[0]
 ...
 await page.pause()
 ... 

```

**Steps**
- [Run the test]
- [...]

**This will pause the page and popup the inspector window.**

[Describe expected behavior]

**The inspector window is blank**

[Describe actual behavior]
<img width="624" alt="image" src="https://github.com/user-attachments/assets/86b6e646-40a5-41fe-b22f-514b49d2561b">

**Comment by KrAsH-CoD3** [comment]
I confirm this bug. Was about creating an issue then I saw this.

**Comment by nwebson** [comment]
You can try [rebrowser-patches](https://github.com/rebrowser/rebrowser-patches), it breaks .pause(), too. But! It allows temporarily disabling the patch via env variable, so you can disable it while debug your stuff, and then turn back again on the fly.

**Comment by espeka44** [comment]
Same issue. Playwright Inspector is blank, and can't record when i "page.pause()".

**Comment by nwebson** [comment]
@espeka44 do you use `process.env.REBROWSER_PATCHES_RUNTIME_FIX_MODE = '0'` when you want to run it for debugging?

**Comment by espeka44** [comment]
@nwebson Yes, tried to.
Nothing change
![image](https://github.com/user-attachments/assets/521eceb1-5b0b-4958-8f80-a95dd73c7509)

**Comment by nwebson** [comment]
@espeka44 please consider creating a new issue in https://github.com/rebrowser/rebrowser-patches/issues and sharing your code, then I can take a deeper look.

**Comment by Vinyzu** [comment]
Solved with Update to Patchright.
@nwebson youre not allowed to advertise your services or your projects under this repository.
