### ISSUE TITLE
[Feature] update to playwright 1.46

### ISSUE THREAD

**Issue by mnogosoka** [Kaliiiiiiiiii-Vinyzu/patchright#21]
have worked version based on 1.40 with some patches (screenY)
tried make update to pw-1.46, but it become detected by cf(
some scripts require add_locator_handle from 1.42

**Comment by nwebson** [comment]
I just released my version of similar patch, it's based on 1.47.0:
[rebrowser-playwright](https://pypi.org/project/rebrowser-playwright/) ([src](https://github.com/rebrowser/rebrowser-playwright-python))

**Comment by danofun** [comment]
> I just released my version of similar patch, it's based on 1.47.0: [rebrowser-playwright](https://pypi.org/project/rebrowser-playwright/) ([src](https://github.com/rebrowser/rebrowser-playwright-python))

Thanks for alerting us to your repo. Looks quite promising! Trying to test and I'm not seeing how to call the patch
from undetected_playwright.sync_api import sync_playwright for this repo
The example shows from playwright.sync_api import sync_playwright but that simply calls the original playwright.

**Comment by mnogosoka** [comment]
> I just released my version of similar patch, it's based on 1.47.0: [rebrowser-playwright](https://pypi.org/project/rebrowser-playwright/) ([src](https://github.com/rebrowser/rebrowser-playwright-python))

cool, but can't pass cloudflare with it, ex. http://0xscore.io

**Comment by nwebson** [comment]
@mnogosoka it works quite fine with cloudflare and passes the captcha with a simple page.click()

**Comment by Vinyzu** [comment]
Solved with Update to Patchright.
@nwebson your not allowed to advertise your services or your projects under this repository.
