### ISSUE TITLE
Unable to pass steamdb

### ISSUE THREAD

**Issue by 2516455367** [Kaliiiiiiiiii-Vinyzu/patchright#25]
![image](https://github.com/user-attachments/assets/2f0c79da-b3fe-4e85-a3d5-80483eee138f)
It can't be a network problem

**Comment by kaliiiiiiiiii** [comment]
@2516455367 please provide a minimum reproducible script.
In addition, have you tried on a different device & IP ?

**Comment by 2516455367** [comment]
> @2516455367请提供最小可重现脚本。 此外，您是否尝试过不同的设备和 IP？


已经解决了 加上这个参数就好了         '--disable-blink-features=AutomationControlled',  But I still can’t get past the details page of Hermès

**Comment by 2516455367** [comment]
> @2516455367请提供最小化的可配置脚本。 此外，您是否尝试过不同的设备和IP？

![12b14e1890f9b1bb0ff20487685359f](https://github.com/user-attachments/assets/ce251c3a-5351-4d54-b478-6b1f2770fbe8)
Has this detection been fixed?

**Comment by kaliiiiiiiiii** [comment]
> @2516455367 please provide a minimum reproducible script. In addition, have you tried on a different device & IP ?

If you don't provide the requested information, I'll have to close this issue as `not planned`

**Comment by Vinyzu** [comment]
Closed as stale.
If the issues persist with patchright aswell, reopen this issue.
Please keep the language under this repository english.
