### ISSUE TITLE
[Feature request] support c#

### ISSUE THREAD

**Issue by rasyidmollan** [Kaliiiiiiiiii-Vinyzu/patchright#29]
How should I migrate to c# to use it

**Comment by Vinyzu** [comment]
Support for C#/.NET is mentioned in the [TODO](https://github.com/Kaliiiiiiiiii-Vinyzu/patchright?tab=readme-ov-file#todo). But i believe it will take some good amount of time before ill implement it.

Community implementations of Patchright are very welcome though!
