### ISSUE TITLE
[Feature request] support `page.addBinding`

### ISSUE THREAD

**Issue by kaliiiiiiiiii** [Kaliiiiiiiiii-Vinyzu/patchright#5]
`page.addBinding(binding_name)` won't work as all scripts are executed in a isolated world.
Relevant source here is [/playwright-core/src/server/chromium/crPage.ts#L828](https://github.com/microsoft/playwright/blob/dd9028cfe24a45de47ab1dfd5aa212537c2629e7/packages/playwright-core/src/server/chromium/crPage.ts#L828)

requires:
- [ ] support javascript with non-isolated worlds
- [ ] support iframes
- [ ] add `isolated` argument
   - [ ] to `addBinding`
   - [ ] to execute-script methods

**Comment by Vinyzu** [comment]
Solved with Update to Patchright.
