### ISSUE TITLE
[BUG] (Action) Selectors do not Work after Manual Content Setting

### ISSUE THREAD

**Issue by Vinyzu** [Kaliiiiiiiiii-Vinyzu/patchright#7]
### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
import asyncio

# undetected-playwright here!
from playwright.async_api import async_playwright, Playwright

async def run(playwright: Playwright):
    args = []

    # disable navigator.webdriver:true flag
    args.append("--disable-blink-features=AutomationControlled")
    browser = await playwright.chromium.launch(headless=False,
                                               args=args)

    context = await browser.new_context()
    page = await context.new_page()
    await page.goto("https://raw.githack.com/microsoft/playwright-python/main/tests/assets/empty.html")
    await page.set_content('<a href="https://raw.githack.com/microsoft/playwright-python/main/tests/assets/one-style.html">yo</a>')
    await page.click("a")
    await page.wait_for_timeout(10000)

async def main():
    async with async_playwright() as playwright:
        await run(playwright)


if __name__ == "__main__":
    loop = asyncio.ProactorEventLoop()
    loop.run_until_complete(main())
```

**Expected**

The Selector should be able to pick up the new inserted content, like it is the case with "normal" playwright.

**Actual**

The Selector doesnt pick up the new content.
Note: Could be explained by a missing isolatedContext consideration.

**Comment by Vinyzu** [comment]
Note:
```py
await page.locator("a").click()
```
Works as expected.

**Comment by Vinyzu** [comment]
Note no.1:
```py
await page.set_content('<iframe src="demo_iframe.htm" height="200" width="300" title="Iframe Example"></iframe> ')
print(page.frame_locator('[title="Iframe Example"]'))
```
Also doesnt work. Other Functions including Selectors maight also not be expected to work

**Comment by kaliiiiiiiiii** [comment]
relevant source code here:
- [NodeJS/`Frame. SetContent`](https://github.com/microsoft/playwright/blob/9d91b7caf51003cb5c11ec0cdeb8431ca0411aa9/packages/playwright-core/src/client/frame.ts#L240)
- https://github.com/kaliiiiiiiiii/undetected-playwright-python/blob/c34fd89b22bf87bfa5082d5203f3d23b9314589f/playwright/_impl/_page.py#L458-L464

**Comment by kaliiiiiiiiii** [comment]
and locator source:
- https://github.com/kaliiiiiiiiii/undetected-playwright-python/blob/c34fd89b22bf87bfa5082d5203f3d23b9314589f/playwright/_impl/_page.py#L732-L746
- https://github.com/kaliiiiiiiiii/undetected-playwright-python/blob/c34fd89b22bf87bfa5082d5203f3d23b9314589f/playwright/_impl/_locator.py#L146-L159
- https://github.com/kaliiiiiiiiii/undetected-playwright-python/blob/c34fd89b22bf87bfa5082d5203f3d23b9314589f/playwright/_impl/_page.py#L677-L691
- https://github.com/kaliiiiiiiiii/undetected-playwright-python/blob/c34fd89b22bf87bfa5082d5203f3d23b9314589f/playwright/_impl/_frame.py#L469-L483
