### ISSUE TITLE
[Feature request] NodeJS support

### ISSUE THREAD

**Issue by abu10512** [Kaliiiiiiiiii-Vinyzu/patchright#8]
cloud you patch the Playwright on nodejs?plz .

**Comment by steinpigs** [comment]
Hoping for a nodejs version of this. Thank you!

**Comment by pim97** [comment]
I have looked into this and you don't need to do much for a nodejs version from my first impression. It's already patching the .js version for you in the python variant and you can copy-paste it into your node-modules and then it works. At least for me : - )

**Comment by Biswajit96** [comment]
anyone using nodejs version ?
i don't understand how to use the nodejs version.

**Comment by nwebson** [comment]
I just made some patch for puppeteer (node version) to fix this issue, to disable `Runtime.Enable`, so it prevents this leak, and works great for DataDome and Cloudflare. 
You can find it in my repo here: https://github.com/rebrowser/rebrowser-patches
🫡 Feel free to open new issue there, I will be happy to take a look and assist.

**Comment by Biswajit96** [comment]
> I just made some patch for puppeteer (node version) to fix this issue, to disable `Runtime.Enable`, so it prevents this leak, and works great for DataDome and Cloudflare. You can find it in my repo here: https://github.com/rebrowser/rebrowser-patches 🫡 Feel free to open new issue there, I will be happy to take a look and assist.

thanks but i'm looking a salutation for playwright

**Comment by nwebson** [comment]
@Biswajit96 playwright patch is available as well now:
Playwright (Node.js): [rebrowser-playwright](https://www.npmjs.com/package/rebrowser-playwright) ([src](https://github.com/rebrowser/rebrowser-playwright)) and [rebrowser-playwright-core](https://www.npmjs.com/package/rebrowser-playwright-core) ([src](https://github.com/rebrowser/rebrowser-playwright-core))
Playwright (Python): [rebrowser-playwright](https://pypi.org/project/rebrowser-playwright/) ([src](https://github.com/rebrowser/rebrowser-playwright-python))

**Comment by Vinyzu** [comment]
Solved with Update to Patchright. (See [patchright-nodejs](https://github.com/Kaliiiiiiiiii-Vinyzu/patchright-nodejs/).
@nwebson youre not allowed to advertise your services or your projects under this repository.
